import type { RouteRecordRaw } from 'vue-router';

export const featureRoutes: RouteRecordRaw[] = [
  {
    path: '/manual-adjustments/:type/:id', name: 'ManualAdjustmentDetail',
    component: () => import('@/views/manual-adjustment/index.vue'),
    meta: { title: '人工调账详情', requiresAuth: true, hidden: true, activeMenu: '/transactions' },
  },
  {
    path: '/account', name: 'Account', component: () => import('@/views/account/index.vue'),
    meta: { title: '账户与安全', icon: 'Lock', requiresAuth: true, hidden: true },
  },
  {
    path: '/notifications',
    name: 'Notifications',
    component: () => import('@/views/notifications/index.vue'),
    meta: { title: '消息中心', icon: 'Bell', requiresAuth: true, hidden: true },
  },
  {
    path: '/dashboard',
    name: 'Dashboard',
    component: () => import('@/views/dashboard/index.vue'),
    meta: {
      title: '营运总览',
      description: '管理代理、资金与审核流程',
      icon: 'Grid',
      requiresAuth: true,
      hidden: false,
    },
  },
  {
    path: '/agent',
    name: 'Agent',
    component: () => import('@/views/agent/index.vue'),
    meta: {
      title: '代理帐户',
      description: '直接新增管理代理帐户',
      icon: 'User',
      requiresAuth: true,
      hidden: false,
    },
  },
  {
    path: '/agent/detail/:id',
    name: 'AgentDetail',
    component: () => import('@/views/agent/detail/index.vue'),
    meta: {
      title: '代理详情',
      description: '查看代理账户、资产余额、业务配置与最近交易',
      icon: 'User',
      requiresAuth: true,
      hidden: true,
      activeMenu: '/agent',
    },
  },
  {
    path: '/currency',
    name: 'Currency',
    component: () => import('@/views/currency/index.vue'),
    meta: {
      title: '幣種管理',
      description: '維護幣種基礎資料與啓停狀態',
      icon: 'Coin',
      requiresAuth: true,
      hidden: false,
    },
  },
  {
    path: '/deposit',
    name: 'Deposit',
    component: () => import('@/views/deposit/index.vue'),
    meta: {
      title: '数字货币入金',
      description: '确认平台已收到USDT或USDC后，审核通过并增加代理余额',
      icon: 'Wallet',
      requiresAuth: true,
      hidden: false,
    },
  },
  {path:'/fiat-deposit',name:'FiatDeposit',component:()=>import('@/views/fiat-deposit/index.vue'),meta:{title:'法币入金',description:'审核代理提交的法币汇款申请',icon:'CreditCard',requiresAuth:true,hidden:false}},
  {path:'/fiat-deposit/detail/:id',name:'FiatDepositDetail',component:()=>import('@/views/fiat-deposit/detail/index.vue'),meta:{title:'法币入金详情',icon:'CreditCard',requiresAuth:true,hidden:true,activeMenu:'/fiat-deposit'}},
  {
    path: '/deposit/detail/:id',
    name: 'DepositDetail',
    component: () => import('@/views/deposit/detail/index.vue'),
    meta: {
      title: '入金详情',
      description: '核对链上交易、代理信息与资金入账影响',
      icon: 'Wallet',
      requiresAuth: true,
      hidden: true,
      activeMenu: '/deposit',
    },
  },
  {
    path: '/exchange',
    name: 'Exchange',
    component: () => import('@/views/exchange/index.vue'),
    meta: {
      title: '兑换审核',
      description: '查看资金冻结和处理时间线后完成一次审核',
      icon: 'Switch',
      requiresAuth: true,
      hidden: false,
    },
  },
  {
    path: '/exchange/detail/:id',
    name: 'ExchangeDetail',
    component: () => import('@/views/exchange/detail/index.vue'),
    meta: {
      title: '兑换详情',
      description: '核对冻结资金、兑换比例与代理余额影响',
      icon: 'Switch',
      requiresAuth: true,
      hidden: true,
      activeMenu: '/exchange',
    },
  },
  {
    path: '/whitelist',
    name: 'Whitelist',
    component: () => import('@/views/whitelist/index.vue'),
    meta: {
      title: '白名单审核',
      description: '四种类型均只需一次审核',
      icon: 'Postcard',
      requiresAuth: true,
      hidden: false,
    },
  },
  {
    path: '/whitelist/detail/:id',
    name: 'WhitelistDetail',
    component: () => import('@/views/whitelist/detail/index.vue'),
    meta: {
      title: '白名单详情',
      description: '核对收付款主体、银行资料与审核风险',
      icon: 'Postcard',
      requiresAuth: true,
      hidden: true,
      activeMenu: '/whitelist',
    },
  },
  {
    path: '/withdrawal',
    name: 'Withdrawal',
    component: () => import('@/views/withdrawal/index.vue'),
    meta: {
      title: '出金管理',
      description: '一次审核后进入付款执行；付款完成不是第二次审核',
      icon: 'Upload',
      requiresAuth: true,
      hidden: false,
    },
  },
  {
    path: '/withdrawal/detail/:id',
    name: 'WithdrawalDetail',
    component: () => import('@/views/withdrawal/detail/index.vue'),
    meta: {
      title: '出金详情',
      description: '核对付款组合、收款主体、佐证文件与资金冻结影响',
      icon: 'Upload',
      requiresAuth: true,
      hidden: true,
      activeMenu: '/withdrawal',
    },
  },
  {
    path: '/fee',
    name: 'Fee',
    component: () => import('@/views/fee/index.vue'),
    meta: {
      title: '比例与费用',
      description: '下方配置将直接影响代理专属费率与帐金额，请谨慎设定。',
      icon: 'Money',
      requiresAuth: true,
      hidden: false,
    },
  },
  {
    path: '/transactions',
    name: 'Transactions',
    component: () => import('@/views/transaction/index.vue'),
    meta: {
      title: '交易记录',
      description: '统一查看入金、兑换与 USD 出金订单',
      icon: 'Tickets',
      requiresAuth: true,
      hidden: false,
    },
  },

  {
    path: '/permission',
    name: 'Permission',
    component: () => import('@/views/permission/index.vue'),
    meta: {
      title: '管理员列表',
      description: '管理可登入後台的管理員帳戶',
      icon: 'User',
      menuGroup: { path: '/access-management', title: '权限管理', icon: 'Lock' },
      requiresAuth: true,
      hidden: false,
    },
  },
  {
    path: '/roles',
    name: 'RoleManagement',
    component: () => import('@/views/role/index.vue'),
    meta: {
      title: '角色管理',
      description: '维护管理端角色与权限范围',
      icon: 'Key',
      menuGroup: { path: '/access-management', title: '权限管理', icon: 'Lock' },
      requiresAuth: true,
      hidden: false,
    },
  },
  {
    path: '/roles/create',
    name: 'RoleCreate',
    component: () => import('@/views/role/form/index.vue'),
    meta: { title: '新增角色', icon: 'Key', requiresAuth: true, hidden: true, activeMenu: '/roles' },
  },
  {
    path: '/roles/:id/edit',
    name: 'RoleEdit',
    component: () => import('@/views/role/form/index.vue'),
    meta: { title: '编辑角色', icon: 'Key', requiresAuth: true, hidden: true, activeMenu: '/roles' },
  },
  {
    path: '/log',
    name: 'Log',
    component: () => import('@/views/log/index.vue'),
    meta: {
      title: '操作记录',
      description: '记录管理员在平台上的所有操作行为',
      icon: 'List',
      requiresAuth: true,
      hidden: false,
    },
  },
  {
    path: '/reservation',
    name: 'Reservation',
    component: () => import('@/views/reservation/index.vue'),
    meta: {
      title: '官網預約',
      description: '查看官網訪客提交的聯絡預約',
      icon: 'Calendar',
      requiresAuth: true,
      hidden: false,
    },
  },
];
