import type { RouteRecordRaw } from 'vue-router';

export const featureRoutes: RouteRecordRaw[] = [
  {
    path: '/dashboard',
    name: 'Dashboard',
    component: () => import('@/views/dashboard/index.vue'),
    meta: {
      title: '营运总览',
      description: '管理代理、资金与审核流程',
      icon: 'Grid',
      requiresAuth: true,
      hidden: false,
      keepAlive: true,
    },
  },
  {
    path: '/agent',
    name: 'Agent',
    component: () => import('@/views/agent/index.vue'),
    meta: {
      title: '代理帐户',
      description: '直接新增管理代理帐户',
      icon: 'User',
      requiresAuth: true,
      hidden: false,
      keepAlive: false,
    },
  },
  {
    path: '/agent/detail/:id',
    name: 'AgentDetail',
    component: () => import('@/views/agent/detail/index.vue'),
    meta: {
      title: '代理详情',
      description: '查看代理账户、资产余额、业务配置与最近交易',
      icon: 'User',
      requiresAuth: true,
      hidden: true,
      keepAlive: false,
      activeMenu: '/agent',
    },
  },
  {
    path: '/currency',
    name: 'Currency',
    component: () => import('@/views/currency/index.vue'),
    meta: {
      title: '币种管理',
      description: '维护币种网络关系、启停状态及平台收款地址',
      icon: 'Coin',
      requiresAuth: true,
      hidden: false,
      keepAlive: false,
    },
  },
  {
    path: '/deposit',
    name: 'Deposit',
    component: () => import('@/views/deposit/index.vue'),
    meta: {
      title: '入金审核',
      description: '确认平台已收到USDT或USDC后，审核通过并增加代理余额',
      icon: 'Wallet',
      requiresAuth: true,
      hidden: false,
      keepAlive: false,
    },
  },
  {
    path: '/deposit/detail/:id',
    name: 'DepositDetail',
    component: () => import('@/views/deposit/detail/index.vue'),
    meta: {
      title: '入金详情',
      description: '核对链上交易、代理信息与资金入账影响',
      icon: 'Wallet',
      requiresAuth: true,
      hidden: true,
      keepAlive: false,
      activeMenu: '/deposit',
    },
  },
  {
    path: '/exchange',
    name: 'Exchange',
    component: () => import('@/views/exchange/index.vue'),
    meta: {
      title: '兑换审核',
      description: '查看资金冻结和处理时间线后完成一次审核',
      icon: 'Switch',
      requiresAuth: true,
      hidden: false,
      keepAlive: false,
    },
  },
  {
    path: '/exchange/detail/:id',
    name: 'ExchangeDetail',
    component: () => import('@/views/exchange/detail/index.vue'),
    meta: {
      title: '兑换详情',
      description: '核对冻结资金、兑换比例与代理余额影响',
      icon: 'Switch',
      requiresAuth: true,
      hidden: true,
      keepAlive: false,
      activeMenu: '/exchange',
    },
  },
  {
    path: '/whitelist',
    name: 'Whitelist',
    component: () => import('@/views/whitelist/index.vue'),
    meta: {
      title: '白名单审核',
      description: '四种类型均只需一次审核',
      icon: 'List',
      requiresAuth: true,
      hidden: false,
      keepAlive: false,
    },
  },
  {
    path: '/whitelist/detail/:id',
    name: 'WhitelistDetail',
    component: () => import('@/views/whitelist/detail/index.vue'),
    meta: {
      title: '白名单详情',
      description: '核对收付款主体、银行资料与审核风险',
      icon: 'List',
      requiresAuth: true,
      hidden: true,
      keepAlive: false,
      activeMenu: '/whitelist',
    },
  },
  {
    path: '/withdrawal',
    name: 'Withdrawal',
    component: () => import('@/views/withdrawal/index.vue'),
    meta: {
      title: '出金管理',
      description: '一次审核后进入付款执行；付款完成不是第二次审核',
      icon: 'Upload',
      requiresAuth: true,
      hidden: false,
      keepAlive: false,
    },
  },
  {
    path: '/withdrawal/detail/:id',
    name: 'WithdrawalDetail',
    component: () => import('@/views/withdrawal/detail/WithdrawalDetailPage.vue'),
    meta: {
      title: '出金详情',
      description: '核对付款组合、收款主体、佐证文件与资金冻结影响',
      icon: 'Upload',
      requiresAuth: true,
      hidden: true,
      keepAlive: false,
      activeMenu: '/withdrawal',
    },
  },
  {
    path: '/fee',
    name: 'Fee',
    component: () => import('@/views/fee/index.vue'),
    meta: {
      title: '比例与费用',
      description: '下方配置将直接影响代理专属费率与帐金额，请谨慎设定。',
      icon: 'Money',
      requiresAuth: true,
      hidden: false,
      keepAlive: false,
    },
  },
  {
    path: '/transactions',
    name: 'Transactions',
    component: () => import('@/views/transaction/index.vue'),
    meta: {
      title: '交易记录',
      description: '统一查看入金、兑换与 USD 出金订单',
      icon: 'Tickets',
      requiresAuth: true,
      hidden: false,
      keepAlive: false,
    },
  },
  {
    path: '/transactions/detail/:businessType/:businessId',
    name: 'TransactionDetail',
    component: () => import('@/views/transaction/detail/index.vue'),
    meta: {
      title: '交易详情',
      description: '统一交易的只读详情',
      icon: 'Tickets',
      requiresAuth: true,
      hidden: true,
      keepAlive: false,
      activeMenu: '/transactions',
    },
  },
  {
    path: '/log',
    name: 'Log',
    component: () => import('@/views/log/index.vue'),
    meta: {
      title: '操作记录',
      description: '记录管理员在平台上的所有操作行为',
      icon: 'List',
      requiresAuth: true,
      hidden: false,
      keepAlive: false,
    },
  },
];
